Can display hello react
dhagandev/Onboarding-UI pull request #7
Opened 2018-08-17 23:09 UTC by dhagandev

2018-08-18 22:53 UTC, kev-chan requested changes
same high level question i asked on Friday:
- why does this work as opposed to other solutions you tried?

2018-08-18 22:53 UTC, kev-chan commented on src/js/react.js
> +if (loadedStates.includes(document.readyState) && document.body) {
what is this entire if/else block used for?

2018-08-18 22:53 UTC, kev-chan commented on src/index.html
> +        <script src="js/react.js"></script>
get a better name, this sounds like it is react you are loading

2018-08-18 22:53 UTC, kev-chan commented on src/js/react.js
> +class App extends React.Component {
why class 'App'?

2018-08-19 02:12 UTC, dhagandev commented
Not sure how to respond directly to the "why does this work as opposed to other solutions you tried?" comment, there is no "reply" like the comments below. But this way works because I am including React and React Dom in the html files. The other ways I had been trying were to add React/React Dom to the js file rendering the React components. Import and require are not implemented in any client side Javascript natively. I hadn't considered adding them to the html originally because it doesn't feel like the best way to be doing this. All the tutorials suggest imports, but mention needing extra libraries like ES6, Babel, etc.

2018-08-20 14:35 UTC, merged