Convert2react
dhagandev/Onboarding-UI pull request #9
Opened 2018-08-27 15:41 UTC by dhagandev

2018-08-27 16:18 UTC, kev-chan requested changes

2018-08-27 16:18 UTC, kev-chan commented on src/js/components.js
> +        e.preventDefault();
why preventDefault() ?

2018-08-27 16:18 UTC, kev-chan commented on src/js/components.js
> +    apiCall() {
should the api call be in this class?

2018-08-27 16:18 UTC, kev-chan commented on src/js/components.js
> +        if (error == null && data == null) {
why only if statements?

2018-08-27 16:18 UTC, kev-chan commented on src/js/components.js
> +                key: "tweetInfo" + this.props.index,
why is there a key on all 'create' calls?

2018-08-27 16:18 UTC, kev-chan commented on src/js/components.js
> +        fetch(apiUrl)
why the switch for how the API call is made?

2018-08-27 16:19 UTC, kev-chan commented on src/js/reactRenderComponents.js
> +        [React.createElement(HeaderComponent, {key: "headerComponent"}, null), React.createElement(BodyComponent, {key: "bodyComponent"}, null)],
why the passing of null?

2018-08-27 16:20 UTC, kev-chan commented on src/scss/styles.scss
> +        .tweetRow:nth-child(odd) {
use scss for these rules

2018-08-27 16:33 UTC, dhagandev commented on src/js/components.js
> +        e.preventDefault();
Removed.

2018-08-27 16:35 UTC, dhagandev commented on src/js/components.js
> +    apiCall() {
I originally had it in the timeline table, but I had no good way of telling the table it needed to make the api call again and update itself when the button was pressed.

2018-08-27 16:36 UTC, dhagandev commented on src/js/components.js
> +        fetch(apiUrl)
I don't understand what you are asking?

2018-08-27 16:38 UTC, dhagandev commented on src/js/components.js
> +                key: "tweetInfo" + this.props.index,
Otherwise it would throw warnings and clutter the console.

2018-08-27 16:40 UTC, dhagandev commented on src/js/components.js
> +        if (error == null && data == null) {
Converted to if/elses.

2018-08-27 17:01 UTC, dhagandev commented on src/js/reactRenderComponents.js
> +        [React.createElement(HeaderComponent, {key: "headerComponent"}, null), React.createElement(BodyComponent, {key: "bodyComponent"}, null)],
The null element represents their children, the children are handled in the Components. This allows for the Dom Render code to be cleaner, I don't need to import/export each component

2018-08-27 17:04 UTC, dhagandev commented on src/js/reactRenderComponents.js
> +        [React.createElement(HeaderComponent, {key: "headerComponent"}, null), React.createElement(BodyComponent, {key: "bodyComponent"}, null)],
Removed nulls.

2018-08-27 21:03 UTC, kev-chan requested changes

2018-08-27 21:03 UTC, kev-chan commented on src/js/components.js
> +export class BodyComponent extends React.Component {
use better variable names overall for handler/getApi

2018-08-27 21:03 UTC, kev-chan commented on src/js/components.js
> +        this.setState({
why did you decide to change the state here?

2018-08-27 21:03 UTC, kev-chan commented on src/js/main.js
>  console.log(`Server running at http://${hostname}:${port}/`);
do you still need the console.log?

2018-08-27 21:05 UTC, dhagandev commented on src/js/components.js
> +        this.setState({
By setting data and error to null here it triggers the waiting screen if it is being slow to receive the api update.

2018-08-27 21:05 UTC, dhagandev commented on src/js/main.js
>  console.log(`Server running at http://${hostname}:${port}/`);
I thought it was good information to have but I can remove it if you feel it isn't necessary.

2018-08-27 21:09 UTC, dhagandev commented on src/js/components.js
> +export class BodyComponent extends React.Component {
Done

2018-08-28 19:31 UTC, kev-chan requested changes

2018-08-28 19:31 UTC, kev-chan commented on src/js/main.js
>  import {run} from './reactRenderComponents.js';
why have main.js only call run?

2018-08-28 19:31 UTC, kev-chan commented on src/js/components.js
> +        apiCall(this.processApiCallResults);
better names for both of these calls

2018-08-28 19:31 UTC, kev-chan commented on src/js/components.js
> +        this.processApiCallResults = this.processApiCallResults.bind(this);
keep the binds together

2018-08-29 14:56 UTC, kev-chan approved these changes

2018-08-29 14:56 UTC, kev-chan commented on src/js/components.js
> +        apiGetTimeline(this.processTimelineResults);
nice the names are much better now

2018-08-29 14:57 UTC, merged